config/routes.rb
Rails.application.routes.draw do

 root to: 'movies#index'

  resources :movies do
    resources :reviews, only: [:new, :create]
  end

  namespace :admin do
    resources :users
  end
  
  resources :users
  resource :session, only: [:new, :create, :destroy]

  get '/admin/change_users/:id', to: 'admin/users#change_user'

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_many :reviews

  validates :title, presence: true
  validates :director, presence: true
  validates :runtime_in_minutes, numericality: {only_integer: true}
  validates :description, presence: true
  validates :poster_image_url, presence: true
  # validates :release_date, presence: true
  validate :release_date_is_in_the_future

  mount_uploader :poster_image_url, AvatarUploader

  scope :search_movie_by_title, ->(title) {where('title like ?', "%#{title}%")}
  scope :search_movie_by_director, ->(director) {where('director like ?', "%#{director}%")}
  scope :search_movie_by_keyword, ->(keyword) {where("title like '%#{keyword}%' OR director like '%#{keyword}%'")}
  scope :search_movie_by_runtime, ->(runtime) { where("runtime_in_minutes #{Movie.movie_by_runtime(runtime)}") }
  scope :search_movie_by_all_categories, ->(title,director,runtime) { where("title like '%#{title}%' AND director like '%#{director}%' AND runtime_in_minutes #{ Movie.movie_by_runtime(runtime) }") }

  def review_average
    if reviews.size > 0
      reviews.sum(:rating_out_of_ten)/reviews.size 
    else
      return 0
    end
  end

  def self.movie_by_runtime(runtime)
    if runtime == "1"
      "< 90"
    elsif runtime == "2"
      "BETWEEN '90' AND '120'"
    elsif runtime == "3"
      "> 120"
    end
  end

  protected
  def release_date_is_in_the_future
    if release_date.present?
      errors.add(:release_date, "should probably be in the future") if release_date < Date.today
    end
  end

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :movie

  validates :user, presence: true
  validates :movie, presence: true
  validates :text, presence: true

  validates :rating_out_of_ten, numericality: {only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 10}

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reviews, dependent: :destroy

  has_secure_password

  validates :email, presence: true
  validates :firstname, presence: true, length: {minimum: 3}
  validates :lastname, presence: true, length: {minimum: 3}
  validates :password, length: {in: 6..20}, on: :create


  def full_name
    "#{firstname} #{lastname}"
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  before_filter :restrict_admin_access

  def index
    @admin_users = User.all.page(params[:page]).per(2)
  end

  def new
    @admin_user = User.new
  end

  def show
    #important to set to integer to avoid malicious user's input that is non integer
    @admin_users = User.find(params[:id].to_i)
  end

  def create
    @admin_user = User.new(admin_user_params)

    if @admin_user.save
      redirect_to admin_users_path, notice: "New user created in admin dashboard, #{@admin_user.email}"
    else
      render :new
    end
  end

  def edit
    @admin_user = User.find(params[:id])
  end

   def change_user
    session[:user_id] = params[:id]
    redirect_to movies_path
  end

  def update
    @admin_user = User.find(params[:id])
    
    if @admin_user.update_attributes(admin_user_params)
      redirect_to admin_users_path
    else
      render :edit
    end

  end

  def destroy
    @admin_user = User.find(params[:id])
    @admin_user.destroy
    UserMailer.goodbye_email(@admin_user)
    redirect_to admin_users_path, notice: "User deleted!"
  end

  protected
  def admin_user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation, :admin)
  end
end



 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def restrict_access
    if !current_user  
      flash[:alert] = "You must log in."
      redirect_to new_session_path
    end
  end

  def restrict_admin_access
    if !session[:impersonated_user_id]
      flash[:alert] = "You are not allowed to access admin panel"
      redirect_to movies_path
    end
  end

  def impersonator
    @impersonator_user ||= User.find(session[:impersonated_user_id]) if session[:impersonated_user_id]
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin
     current_user.admin?
  end

  # def change_current_user(selected_user)
  #   if current_user != selected_user
  #     current_user = User.find_by(email: selected_user.email)
  #     puts "selected_user's email = #{selected_user.email}"
  #   end
  # end

  helper_method :current_user, :current_admin, :impersonator
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index
    
    if params[:keyword] && params[:runtime_in_minutes] == "0"
      @movies = Movie.search_movie_by_keyword(params[:keyword])
    elsif params[:runtime_in_minutes] && params[:keyword].empty?
      @movies = Movie.search_movie_by_runtime(params[:runtime_in_minutes])
    elsif params[:keyword] && params[:runtime_in_minutes]
      @movies = Movie.search_movie_by_all_categories(params[:keyword],params[:runtime_in_minutes])
    else
      @movies = Movie.all
    end

    @user = current_user
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to movies_path, notice: "#{@movie.title} was submitted successfully!"
    else
      render :new
    end
  end

  def update
    @movie = Movie.find(params[:id])

    if @movie.update_attributes(movie_params)
      redirect_to movie_path(@movie)
    else
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_path
  end

  protected

  def movie_params
    params.require(:movie).permit(
      :title, :release_date, :director, :runtime_in_minutes, :poster_image_url, :description
    )
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_filter :load_movie
  before_filter :restrict_access

  def new
    @movie = Movie.find(params[:movie_id])
    @review = @movie.reviews.build
  end

  def create
    @movie = Movie.find(params[:movie_id])
    @review = @movie.reviews.build(review_params)
    @review.user_id = current_user.id

    if @review.save
      redirect_to @movie, notice: "Review created successfully"
    else
      render :new
    end
  end

  protected

  def load_movie
    @movie = Movie.find(params[:movie_id])
  end

  def review_params
    params.require(:review).permit(:text, :rating_out_of_ten)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      session[:impersonated_user_id] = user.id if user.admin?
      redirect_to movies_path, notice: "Welcome back, #{user.firstname}"
    else
      flash.now[:alert] = "Log in failed..."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to movies_path, notice: "Adios!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @users = User.all
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    if current_user.admin?
      session[:impersonated_user_id] = @user.id
    end
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to movies_path, notice: "Welcome aboard, #{@user.firstname}!"
    else
      render :new
    end
  end

  def change_user
    session[:user_id] = params[:id]
    redirect_to movies_path
  end

  protected
  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation)
  end

  
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  def formatted_date(date)
    date.strftime("%b %d, %Y")
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<div class="container">
  <div class="row">
  <%= bootstrap_form_for([:admin, @admin_user]) do |f| %>
     <% if @admin_user.errors.any? %>
      <div>
        <%= pluralize(@admin_user.errors.count, "error")%> prevented this from movie being submitted:
        <ul>
          <% @admin_user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
     <% end %>
      <%= f.text_field :title %>
      <%= f.text_field :director %>
      <%= f.email_field :email %>
      <%= f.password_field :password %>
      <%= f.password_field :password_confirmation %>
      <%= f.check_box :admin %>
      <%= f.submit "Submit" %>
    <% end %>
  </div>
</div>

app/views/admin/users/create.html.erb
<h1>Admin#create</h1>
<p>Find me in app/views/admin/create.html.erb</p>

app/views/admin/users/edit.html.erb
<%= link_to "Back to user list", admin_users_path %>

<h2>Edit this user:</h2>

<%= render 'form' %>

app/views/admin/users/index.html.erb
<h1>ADMIN PANEL</h1>
<div class="container">
  <div class="row">
    <%= paginate @admin_users %>
    
    <div class="panel panel-default panel-info">
      <div class="panel-heading">LIST OF ALL USERS</div>
        <table class="table">
          <tr>
            <td><strong>Firstname</strong></td>
            <td><strong>Lastname</strong></td>
            <td><strong>Email</strong></td>
            <td><strong>Admin?</strong></td>
            <td><strong>Config</strong></td>
          </tr>

        <% @admin_users.each do |user| %>
          <tr>
             <td><%= user.firstname %></td>
             <td><%= user.lastname %></td>
             <td><%= user.email %></td>
             <td><%= user.admin? %></td>
             <td>
              <%= link_to "Edit User",  edit_admin_user_path(user) %> |
              <%= link_to "Delete User",  admin_user_path(user), method: :delete, confirm: "You sure?" %> 
              <% if !user.admin? %>
               <!--  | <%= link_to "Switch to user", user_path(user.id) %> -->
               <%= link_to "Switch to user", "/admin/change_users/#{user.id}" %>
              <% end %>
             </td>
          </tr>
        <% end %>
        </table>
    </div><!--END OF PANEL DIV-->
  </div><!--END OF ROW DIV-->

  <div class="row">
  <button type="button" class="btn btn-info"><%= link_to "Create new user", new_admin_user_path %></button>
  </div>
</div>

app/views/admin/users/new.html.erb
<%= link_to "Back to user list", admin_users_path %>

<h2>Create new user:</h2>

<%= render 'form' %>

app/views/layouts/_footer.html.erb
<footer style="padding-bottom:50px;">
  <small>
    <% if current_user %>
      Signed in as  <%= current_user.full_name %> (<%= link_to "Log out", session_path("current"), method: :delete %>)
    <% else %>
      <%= link_to "Log In", new_session_path %> | <%= link_to "Sign Up", new_user_path %>
    <% end %>
    <% if session[:impersonated_user_id] %>
      <% if session[:user_id] != session[:impersonated_user_id] %>
       <%= link_to "Return to yourself" , "admin/change_users/#{session[:impersonated_user_id]}" %>
      <% end %>
      <%= link_to "Admin Panel", admin_users_path %>
    <% end %>
  </small>  
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RottenMangoes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
<div class="container">
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value) %>
  <% end %>
  <div class="row">
    <%= yield %>
  </div>
  <div class="row">
    <%= render 'layouts/footer' %>
  </div>
</div>
</body>
</html>

app/views/movies/_form.html.erb
<div class="container">
  <div class="row">
  <%= bootstrap_form_for(@movie, :html => {:multipart => true}) do |f| %>
     <% if @movie.errors.any? %>
      <div>
        <%= pluralize(@movie.errors.count, "error")%> prevented this from movie being submitted:
        <ul>
          <% @movie.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
     <% end %>
      <%= f.text_field :title %>
      <%= f.date_field :release_date %>
      <%= f.text_field :director %>
      <%= f.number_field :runtime_in_minutes %>
      <%= f.file_field :poster_image_url %>
      <%= f.text_area :description %>
      <%= f.submit "Submit" %>
    <% end %>
  </div>
</div>

app/views/movies/_movie.html.erb
<%= link_to movie.title, movie_path(movie), class: "list-group-item active" %>
<span class="list-group-item"><%= link_to image_tag(movie.poster_image_url.url(:thumb).to_s), movie_path(movie) %></span>
<span class="list-group-item"><%= formatted_date(movie.release_date) %></span>
<span class="list-group-item">Dir. <%= movie.director %> | <%= movie.runtime_in_minutes %> minutes</span>
<span class="list-group-item"><%= movie.description %></span>

app/views/movies/edit.html.erb
<%= link_to "Back to this movie", movie_path(@movie) %>

<h2>Edit this movie:</h2>
<%= render 'form' %>

app/views/movies/index.html.erb
<div class="container">
  <div class="row">
    <h1>Rotten Mangoes</h1>
    <button type="button" class="btn btn-info"><%= link_to "Submit a movie!", new_movie_path %></button>
    <button type="button" class="btn btn-info"><%= link_to "Your Profile", user_path(@user) %></button>
    <hr>
    <%= form_tag movies_path, :method => 'get' do %>
      <%= label_tag(:q, "Search for: ") %><br/>
      <%= text_field_tag :keyword %><br/>
      <%= label_tag(:q, "Runtime: ") %>  <%= select_tag(:runtime_in_minutes, options_for_select([['Please select', 0],['Under 90 minutes', 1], ['Between 90 and 120 minutes', 2],['Over 120 minutes', 3]],0)) %><br/>
          <%= submit_tag "Search", :name => nil %>
    <% end %>
    <hr>
    Search Results:
    <% @movies.each do |movie| %>
      <div class="list-group">
        <%= render partial: "movie", locals: {movie: movie} %> 
      </div>
    <% end %>
  </div>
</div>

app/views/movies/new.html.erb
<div class="container">
  <% if current_user %>
      <% if current_admin %>
        <%= link_to "Back to Admin panel", admin_users_path %> | 
    <% end %>
  <% end %> 
  <%= link_to "Back to all movies", movies_path %>

  <h2>Submit a movie!</h2>
  <%= render 'form' %>
</div>

app/views/movies/show.html.erb
<div class="container">
  <div class="row">
    <% if current_user %>
      <% if current_admin %>
        <%= link_to "Back to Admin panel", admin_users_path %> | 
      <% end %>
    <% end %> 
    <%= link_to "Back to all movies" , movies_path %>
  
    <div class="panel panel-warning">
      <div class="panel-heading"><%= @movie.title %> <%= link_to "edit", edit_movie_path(@movie)%> | <%= link_to "delete", movie_path(@movie), method: :delete, confirm: "You sure?" %></div>
       <div class="panel-body">
        <%= link_to image_tag(@movie.poster_image_url.url(:thumb).to_s), movie_path(@movie) %>
        <h3><%= formatted_date(@movie.release_date) %></h3>
        <h4>Dir. <%= @movie.director %> | <%= @movie.runtime_in_minutes %> minutes</h4>
        <p><%= @movie.description %></p>
      </div>
    </div>
  </div>
  <div class="row">
     <div class="panel panel-warning">
      <div class="panel-heading">Reviews of <em><%= @movie.title %></em></div>
      <div class="panel-body">
    <p><em>Review Average</em> : <%= @movie.review_average %>/10</p>
    <% if current_user %>
      <% @movie.reviews.each do |review| %>
        <hr/>
        <p><%= review.text %></p>
        <p>My rating: <%= review.rating_out_of_ten %>/10</p>
        <small>- <%= review.user.full_name%></small><br/>
        <hr/>
      <% end %>
      <button type="button" class="btn btn-warning"><%= link_to "Write a review!", new_movie_review_path(@movie) %></button>
    <% else %>
      <p>Please <%= link_to "log in", new_session_path %> to see reviews and add your own.</p>
    <% end %>
    </div>
  </div>
</div>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<div class="container">
  <div class="row">
    <%= link_to "Back to movie", movie_path(@movie) %> <br/>
    <h2>Write a review of <em><%= @movie.title %></em>. </h2>
  </div>
  <div class="row">
  <%= bootstrap_form_for([@movie, @review]) do |f| %>
      <% if @review.errors.any? %>
        <div>
          <%= pluralize(@review.errors.count, "error") %> prevented this from being saved:
          <ul>
            <% @review.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= f.text_area :text %>
      <%= f.number_field :rating_out_of_ten %>
      <%= f.submit "Submit" %>
    <% end %>
  </div>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<div>
  List of all users:
  <table class="table">
      <tr>
        <td>Firstname</td>
        <td>Lastname</td>
        <td>Email</td>
      </tr>
  <% @users.each do |user| %>
      <tr>
        <td><%= user.firstname %></td>
        <td><%= user.firstname %></td>
        <td><%= user.email %></td>
      </tr>
  <% end %>
   </table>
</div>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div>
      <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label "email" %><br/>
    <%= f.text_field "email" %><br/>
  </div>

  <div>
    <%= f.label "firstname" %><br/>
    <%= f.text_field "firstname" %><br/>
  </div>

  <div>
    <%= f.label "lastname" %> <br/>
    <%= f.text_field "lastname" %><br/>
  </div>

  <div>
    <%= f.label "password" %><br/>
    <%= f.password_field "password" %><br/>
  </div>

  <div>
    <%= f.label "password_confirmation" %><br/>
    <%= f.password_field "password_confirmation" %><br/>
  </div>

  <div><%= f.submit "Submit" %></div>

<% end %>

app/views/users/show.html.erb
 <% if current_user %>
      <% if current_admin %>
        <%= link_to "Back to Admin panel", admin_users_path %>
      <% end %>
    <% end %> <br/>
    <% if impersonator %>
       <strong>You're currently signed in as an impersonator of</strong> <%= impersonator.full_name %>
    <% end %>


<div class="panel panel-success">
  <div class="panel-heading">Your Profile</div>
   <div class="panel-body">
    <table class="table">
      <tr>
        <td>Firstname</td>
        <td><%= @user.firstname %></td>
      </tr>
      <tr>
        <td>Lastname</td>
        <td><%= @user.lastname %></td>
      </tr> 
      <tr>
        <td>Email</td>
        <td><%= @user.email %></td>
      </tr>  
      <tr>
        <td>Movie Reviews</td>
        <td>
          <% if @user.reviews.any? %>
            <% @user.reviews.each do |review| %>
              <p><strong><%= review.movie.title %></strong><br/>
              <%= review.text%></p>
              <br/>
            <% end %>
          <% end %>
        </td>
      </tr>
    </table>
  </div>
</div>

 